/* eslint-disable @typescript-eslint/no-require-imports */
const assert = require('node:assert/strict');
const load = require('./load.cjs');
const {seed, visible} = load('lib/model.ts');
const {applyCoordination} = load('lib/coordination.ts');
const {advisersNow, madridMinute, nextMinute} = load('lib/advisers.ts');
const owner = {id: 'root', name: 'Root', role: 'root', status: 'active'};
const admin = {id: 'admin', name: 'Admin', role: 'admin', status: 'active'};
const a = {id: 'a', name: '538 Miguel', role: 'delegate', status: 'active'};
const b = {id: 'b', name: '620', role: 'delegate', status: 'active'};
const c = {id: 'c', name: '4819', role: 'delegate', status: 'active'};
const day = '2026-09-28T';
const instant = new Date('2026-09-28T12:00:00.000Z'); // 14:00 Barcelona
const sh = (id, userId, start, end) => ({id, userId, start: day + start, end: day + end, status: 'confirmed'});
const fresh = () => {const s = seed(owner); s.users = [owner, admin, a, b, c]; s.shifts = [sh('one','a','13:30','18:00')]; return s;};
const apply = (s, u, action, at = instant) => applyCoordination(s, u, action, at);
let s = fresh();
assert.equal(madridMinute(instant), day + '14:00');
for (const zone of ['UTC','America/Los_Angeles','Europe/Madrid']) {process.env.TZ = zone; assert.equal(madridMinute(instant), day + '14:00');}
assert.equal(madridMinute(new Date('2026-12-01T12:30:00Z')), '2026-12-01T13:30');
assert.equal(nextMinute(new Date('2026-09-28T12:00:01Z')), day + '14:01');
assert.equal(advisersNow(s, day + '14:00').people[0].userId, 'a');
assert.equal(advisersNow(s, day + '18:00').people.length, 0);
s.shifts.push(sh('overlap','a','14:00','16:00'), sh('two','b','14:00','15:30'), sh('next','b','19:00','21:00'));
assert.equal(advisersNow(s, day + '14:00').people.length, 2);
assert.equal(advisersNow(s, day + '14:00').nextChange, day + '15:30');
assert.equal(advisersNow(s, day + '14:00').nextEnd, day + '15:30');
assert.equal(advisersNow(s, day + '14:00').nextStart, day + '19:00');
assert.equal(advisersNow(s, day + '18:30').gapSince, day + '18:00');
assert.deepEqual(advisersNow(s, day + '14:00').upcoming.map(p => [p.start.slice(11),p.end.slice(11),p.userIds.join('/')]), [['14:00','15:30','a/b'],['15:30','18:00','a'],['18:00','19:00',''],['19:00','20:00','b']]);
s.shifts = [{id:'night',userId:'a',start:'2026-09-27T23:30',end:day+'07:15',status:'confirmed'}];
assert.equal(advisersNow(s, day + '00:01').people.length, 1);
assert.equal(advisersNow(s, day + '07:15').people.length, 0);
s.shifts = [sh('one','a','13:30','15:00'), sh('adjacent','a','15:00','18:00')];
assert.equal(advisersNow(s, day + '14:00').nextChange, day + '18:00');
for (const status of ['available','busy','away']) {
 const events = apply(s, a, {type:'adviser.status',status});
 assert.equal(events[0].type, 'adviser_status_changed');
 assert.equal(advisersNow(s, day + '14:00').people[0].status,status);
 assert.equal(advisersNow(s, day + '15:00').people[0].status,status);
}
assert.equal(advisersNow(s, day + '18:00').people.length,0);
assert.throws(() => apply(s,b,{type:'adviser.status',status:'busy'}), /activo/);
assert.throws(() => apply(s,a,{type:'adviser.status',status:'offline'}), /válido/);
assert.throws(() => apply(s,admin,{type:'adviser.status',userId:'a',status:'busy'}), /propio/);
assert.throws(() => apply(s,{...a,status:'blocked'},{type:'adviser.status',status:'busy'}), /autorizado/);
assert.throws(() => apply(s,a,{type:'substitution.request',shiftId:'adjacent',from:day+'16:00'}), /activo/);
assert.throws(() => apply(s,b,{type:'substitution.request',shiftId:'one',from:day+'14:30'}), /ajenos/);
assert.throws(() => apply(s,a,{type:'substitution.request',shiftId:'one',from:day+'13:59'}), /retroceder/);
s = fresh();
const original = structuredClone(s.shifts[0]);
let events = apply(s,a,{type:'substitution.request',shiftId:'one',from:day+'16:30',reason:'Privado'});
assert.equal(events[0].type,'substitution_requested');
const r = s.substitutions[0];
assert.deepEqual(r.originalShift,original);
assert.equal(visible(s,b).substitutions[0].reason,undefined);
assert.equal(visible(s,b).substitutions[0].originalShift,undefined);
assert.equal(visible(s,admin).substitutions[0].reason,'Privado');
assert.equal(visible(s,a).substitutions[0].reason,'Privado');
assert.throws(() => apply(s,a,{type:'substitution.request',shiftId:'one',from:day+'16:45'}), /pendiente/);
assert.throws(() => apply(s,a,{type:'substitution.accept',id:r.id}), /propia/);
assert.throws(() => apply(s,b,{type:'substitution.accept',id:r.id,userId:'c'}), /propia cuenta/);
assert.throws(() => apply(s,b,{type:'substitution.cancel',id:r.id}), /ajenas/);
s.shifts.push(sh('overlapping-b','b','16:00','17:00'));
events = apply(s,b,{type:'substitution.accept',id:r.id});
assert.equal(r.status,'accepted');
assert.equal(s.shifts.find(x => x.id === 'one').end,day+'16:30');
assert.equal(s.shifts.find(x => x.substitutionId === r.id).end,day+'18:00');
assert.deepEqual(r.originalShift,original);
assert.equal(r.acceptedBy,'b');
assert.equal(r.requestedBy,'a');
assert.equal(events.filter(e => e.type === 'substitution_accepted').length,1);
assert.deepEqual(advisersNow(s,day+'16:30').people.map(p => p.userId),['b']);
assert.throws(() => apply(s,c,{type:'substitution.accept',id:r.id}), /cambiado/);
assert.throws(() => apply(s,admin,{type:'substitution.cancel',id:r.id}), /pendientes/);
assert.throws(() => apply(s,a,{type:'shift.edit',id:'one',start:original.start,end:original.end}), /relevo/);
s = fresh();
apply(s,admin,{type:'substitution.request',shiftId:'one',from:day+'14:30'});
assert.equal(s.substitutions[0].requestedBy,'admin');
apply(s,b,{type:'substitution.accept',id:s.substitutions[0].id},new Date('2026-09-28T13:45:23Z'));
assert.equal(s.substitutions[0].effectiveFrom,day+'15:46');
assert.equal(s.shifts[0].end,day+'15:46');
s = fresh(); apply(s,a,{type:'substitution.request',shiftId:'one',from:day+'17:00'});
assert.throws(() => apply(s,b,{type:'substitution.accept',id:s.substitutions[0].id},new Date('2026-09-28T16:00:00Z')), /terminado/);
apply(s,admin,{type:'substitution.cancel',id:s.substitutions[0].id});
assert.equal(s.substitutions[0].status,'cancelled'); assert.equal(s.shifts[0].end,day+'18:00');
s = fresh(); apply(s,a,{type:'substitution.request',shiftId:'one',from:day+'17:00'});
apply(s,a,{type:'shift.edit',id:'one',start:day+'13:30',end:day+'17:30'});
assert.equal(s.substitutions[0].status,'cancelled');
assert.throws(() => apply(s,b,{type:'shift.edit',id:'one',start:day+'13:30',end:day+'17:00'}), /ajenos/);
assert.throws(() => apply(s,b,{type:'shift.delete',id:'one'}), /ajenos/);
assert.throws(() => apply(s,a,{type:'shift.edit',id:'one',userId:'b',start:day+'13:30',end:day+'17:00'}), /reasignar/);
events=apply(s,a,{type:'shift.delete',id:'one'});
assert.equal(s.shifts.length,1);assert.equal(s.shifts[0].status,'cancelled');
assert.ok(events.some(e => e.type === 'coverage_gap'));
assert.equal(advisersNow(s,day+'14:00').people.length,0);
assert.throws(() => apply(s,a,{type:'coverage.claim',userId:'b',end:day+'15:00'}), /cuenta/);
apply(s,a,{type:'coverage.claim',end:day+'15:15'});
assert.equal(advisersNow(s,day+'14:00').people[0].userId,'a');
assert.equal(s.shifts[1].start,day+'14:00');
assert.throws(() => apply(s,b,{type:'coverage.claim',end:day+'15:00'}), /cambiado/);
s = fresh(); s.users=s.users.map(u=>u.id==='a'?{...u,status:'blocked'}:u);
assert.equal(advisersNow(s,day+'14:00').people.length,0);
assert.equal(applyCoordination(s,a,{type:'unrelated'}),null);
console.log('PASS: 65+ assertions — Madrid clock, minutes/midnight, gaps, overlaps, adjacent slots, statuses, own/admin permissions, substitutions, privacy, late acceptance, immutable originals, claim and event snapshots.');

const {apply: applyAction} = load('lib/actions.ts');
s = fresh(); s.users=s.users.map(u=>u.id==='a'?{...u,status:'blocked'}:u);
s.shifts=Array.from({length:7},(_,i)=>({id:'blocked-'+i,userId:'a',status:'confirmed',start:load('lib/model.ts').dateAdd('2026-09-28',i)+'T00:00',end:load('lib/model.ts').dateAdd('2026-09-28',i+1)+'T00:00'}));
applyAction(s,admin,{type:'coverage.send',week:'2026-09-28'});
assert.equal(s.coverageRequests[0].week,'2026-09-28');
s=fresh();apply(s,a,{type:'adviser.status',status:'busy'});apply(s,a,{type:'substitution.request',shiftId:'one',from:day+'16:30'});apply(s,b,{type:'substitution.accept',id:s.substitutions[0].id});
assert.equal(advisersNow(s,day+'14:00').people.find(p=>p.userId==='a').status,'busy');
assert.equal(s.adviserStatuses[0].until,day+'16:30');
console.log('PASS: inactive users excluded from coverage alerts; future handoff preserves busy status until relief.');
