/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require('node:assert/strict'),fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');const load=require('./load.cjs');const {seed}=load('lib/model.ts');const {applyReservations}=load('lib/reservations.ts');
(async()=>{
 const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create schema storage;create table storage.buckets(id text,name text,public boolean,file_size_limit bigint);`);
 await db.exec(fs.readFileSync('supabase/schema.sql','utf8'));for(const f of fs.readdirSync('supabase/migrations').sort())await db.exec(fs.readFileSync('supabase/migrations/'+f,'utf8'));
 const admin={id:'central',role:'admin',status:'active',name:'Central'},a={id:'a',role:'reservation',status:'active',reservationTypes:['MONOVOLUMEN'],memberId:'m'},b={...a,id:'b'};
 const s=seed(admin);s.users=[admin,a,b];s.members=[{id:'m',status:'active'}];s.shifts=[];
 const call=(v,s,e)=>db.query('select public.tx_commit_reservations($1,$2,$3)',[v,JSON.stringify(s),JSON.stringify(e)]);const read=async()=>(await db.query('select public.tx_load_reservations() p')).rows[0].p;
 for(const role of ['anon','authenticated']){await db.exec('set role '+role);for(const table of ['tx_reservations','tx_reservation_events','tx_reservation_mail'])await assert.rejects(db.query('select * from '+table),/permission denied/);await assert.rejects(db.query('select public.tx_claim_reservation_mail()'),/permission denied/);await assert.rejects(read(),/permission denied/);await assert.rejects(call(0,s,[]),/permission denied/);await db.exec('reset role')}
 await db.exec('set role service_role');let e=applyReservations(s,admin,{type:'reservation.save',start:new Date(Date.now()+7200000).toISOString(),kind:'MONOVOLUMEN',pickup:'A',destination:'B'});const id=s.reservations[0].id;e.push(...applyReservations(s,admin,{type:'reservation.publish',id}));await call(0,s,e);
 let snap=await read();const one=structuredClone(snap.state),two=structuredClone(snap.state);const ea=applyReservations(one,a,{type:'reservation.accept',id,confirm:true}),eb=applyReservations(two,b,{type:'reservation.accept',id,confirm:true});
 const results=await Promise.allSettled([call(snap.version,one,ea),call(snap.version,two,eb)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.match(results.find(r=>r.status==='rejected').reason.message,/TX_CONFLICT/);
 snap=await read();assert.equal(snap.state.reservations[0].assignedTo,'a');assert.equal((await db.query('select count(*)::int n from tx_reservation_mail')).rows[0].n,1);
 const claims=await Promise.all([db.query('select * from tx_claim_reservation_mail()'),db.query('select * from tx_claim_reservation_mail()')]);assert.equal(claims.reduce((n,r)=>n+r.rows.length,0),1);
 const job=claims.flatMap(r=>r.rows)[0];assert.equal(job.attempts,1);
 await db.query("update tx_reservation_mail set lease_until=now()-interval '1 minute' where id=$1",[job.id]);const retry=(await db.query('select * from tx_claim_reservation_mail()')).rows[0];assert.equal(retry.id,job.id);assert.notEqual(retry.lease,job.lease);
 await db.query("update tx_reservation_mail set first_attempt_at=now()-interval '24 hours',lease_until=now()-interval '1 minute'");assert.equal((await db.query('select * from tx_claim_reservation_mail()')).rows.length,0);assert.equal((await db.query('select state from tx_reservation_mail')).rows[0].state,'review');
 await assert.rejects(db.query('delete from tx_reservation_events'),/permission denied/);await assert.rejects(db.query("update tx_reservation_events set event='{}'"),/permission denied/);
 const before=snap.version;await assert.rejects(call(before,snap.state,[{type:'reservation.invalid',id:'bad'}]),/uuid/);assert.equal((await read()).version,before);
 e=applyReservations(snap.state,admin,{type:'reservation.republish',id});await call(snap.version,snap.state,e);snap=await read();e=applyReservations(snap.state,b,{type:'reservation.accept',id,confirm:true});await call(snap.version,snap.state,e);assert.equal((await db.query('select count(*)::int n from tx_reservation_mail')).rows[0].n,2);
 snap=await read();e=applyReservations(snap.state,b,{type:'reservation.release',id,reason:'No puedo'});await call(snap.version,snap.state,e);assert.equal((await db.query("select count(*)::int n from tx_reservation_mail where state='pending'")).rows[0].n,0);assert.equal((await read()).state.reservations[0].assignedTo,'b');
 await db.close();console.log('PASS: local PostgreSQL migrations, browser denial, concurrent accept winner, immutable audit, rollback, unique outbox, concurrent claims, lease recovery, bounded retries, reassign and renunciation.');
})().catch(e=>{console.error(e);process.exitCode=1});
