const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const load=require('./load.cjs');
const model=load('lib/model.ts'),{apply}=load('lib/actions.ts');
const rootUser={id:'owner',name:'Owner',role:'root',status:'active'};
const admin={id:'admin',name:'Admin',role:'admin',status:'active'};
const delegate={id:'delegate',name:'Delegate',role:'delegate',status:'active'};
const state=model.seed(rootUser);state.users.push(admin,delegate);
const member=state.members[0],other=state.members[1];
const action={type:'restriction.save',memberId:member.id,kind:'sanction',title:'Sin servicios',reason:'Registro de prueba',start:'2026-09-20T09:00',end:'2026-09-21T09:00'};
assert.throws(()=>apply(state,delegate,action),/administración/);
apply(state,admin,action);
const r=member.restrictions[0];assert.equal(r.author,'admin');assert.equal(model.visible(state,delegate).members[0].restrictions[0].title,'Sin servicios');
assert.throws(()=>apply(state,delegate,{...action,id:r.id,title:'Cambio no autorizado'}),/administración/);
assert.throws(()=>apply(state,admin,{...action,id:r.id,start:'2026-02-30T10:00'}),/fechas/);
assert.throws(()=>apply(state,admin,{...action,id:r.id,end:action.start}),/fechas/);
assert.throws(()=>apply(state,admin,{...action,memberId:other.id,id:r.id}),/registro/);
apply(state,admin,{...action,id:r.id,kind:'incompatibility',title:'Abonado 6464',end:''});
assert.equal(r.history[0].previous.title,'Sin servicios');assert.equal(r.title,'Abonado 6464');assert.equal(r.end,'');
apply(state,admin,{type:'member.edit',id:member.id,model:'Vehículo actualizado'});
assert.throws(()=>apply(state,delegate,{type:'restriction.delete',memberId:member.id,id:r.id}),/administración/);
apply(state,rootUser,{type:'restriction.delete',memberId:member.id,id:r.id});
assert.equal(model.visible(state,delegate).members[0].restrictions.length,0);
assert.equal(model.visible(state,delegate).members[0].history[0].previous.restrictions,undefined);
assert.equal(model.visible(state,admin).members[0].restrictions[0].history.length,2);
assert.throws(()=>apply(state,admin,{...action,id:r.id}),/borrado/);
apply(state,admin,{...action,kind:'incompatibility',title:'Priority',end:''});
apply(state,admin,{type:'import',members:[{fleet:'NEW-FLEET',license:member.license,name:'Nuevo titular',plate:'DEMO',model:'Modelo',requirements:[],drivers:[]}]});
assert.equal(member.status,'inactive');assert.equal(member.restrictions.length,2);
assert.equal(state.members.find(m=>m.fleet==='NEW-FLEET').restrictions,undefined);
assert.equal(model.visible(state,delegate).members[0].restrictions.length,1);
for(const file of ['actions.ts','model.ts','schedule.ts','advisers.ts','coordination.ts'])assert.equal(fs.readFileSync(path.join(root,'supabase/functions/taximes-api',file),'utf8'),fs.readFileSync(path.join(root,'lib',file),'utf8').replace(/from '(\.\/[^']+)'/g,"from '$1.ts'"));
console.log('PASS: admin/root CRUD, delegate rejection, dates, audit, deleted privacy, import history, licence sale isolation, edge source parity.');
