'use client';
import {profileLabel} from '@/lib/user-profiles';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useState} from 'react';
import {type Item,type State,isAdmin} from '@/lib/model';
import {reservationTypes} from '@/lib/reservations';
import {calendarDays,madridISO,madridLocal} from '@/lib/reservation-calendar';
import {apiFetch,supabase} from '@/lib/supabase-client';
import {toast,Toaster} from 'sonner';
const names:Record<string,string>={pending:'Pendiente',assigned:'Asignado',completed:'Realizado',cancelled:'Cancelado'};
const empty={kind:'MONOVOLUMEN',start:'',pickup:'',destination:'',observations:'',requirements:'',customerType:'',passengers:''};
type Props={state:State;user:Item;busy:boolean;ready:boolean;act:(a:Item)=>Promise<boolean>};
export default function Reservations({state:s,user,busy,ready,act}:Props){
 const admin=isAdmin(user);
 const [tab,setTab]=useState('available'),[mode,setMode]=useState('week'),[day,setDay]=useState(madridLocal(new Date().toISOString()).slice(0,10)),[filter,setFilter]=useState('all');
 const [form,setForm]=useState<Item|null>(null),[confirm,setConfirm]=useState<Item|null>(null),[reason,setReason]=useState(''),[access,setAccess]=useState<Item>({userId:'',memberId:'',reservationTypes:[],status:'active'}),[events,setEvents]=useState<Item[]>([]),[cursor,setCursor]=useState<string|null>(null),[historyLoaded,setHistoryLoaded]=useState(false),[historyBusy,setHistoryBusy]=useState(false);
 const rows=(s.reservations||[]).filter(r=>filter==='all'||r.status===filter).sort((a,b)=>a.start.localeCompare(b.start));
 async function history(more=false){setHistoryBusy(true);try{const r=await apiFetch('/api/reservation-history'+(more&&cursor?'?before='+cursor:''));const j=await r.json() as Item;if(!r.ok)throw Error(j.error);setEvents(more?[...events,...j.events]:j.events);setCursor(j.nextCursor);setHistoryLoaded(true)}catch(e){toast.error((e as Error).message)}finally{setHistoryBusy(false)}}
 async function save(){if(!form)return;try{if(await act({...form,type:'reservation.save',start:madridISO(form.start)}))setForm(null)}catch(e){toast.error((e as Error).message)}}
 const ask=(type:string,r:Item)=>{setReason('');setConfirm({type,id:r.id,kind:r.kind,start:r.start,pickup:r.pickup,destination:r.destination})};
 const card=(r:Item)=><article key={r.id} className={'reservation-card '+r.status}><div className="reservation-meta"><strong>{r.kind==='ADAPTADO'?'♿':'🚐'} {r.kind}</strong><span className={'tag '+r.status}>{r.status==='pending'&&r.published?'DISPONIBLE':names[r.status]}</span></div><h3>{madridLocal(r.start).replace('T',' · ')} <small>Madrid</small></h3><p><b>Recogida:</b> {r.pickup}</p><p><b>Destino:</b> {r.destination}</p><p>{r.customerType}{r.passengers?` · ${r.passengers} pasajeros`:''}</p>{r.requirements&&<p><b>Requisitos:</b> {r.requirements}</p>}{r.observations&&<p>{r.observations}</p>}{r.assignedTo&&<p><b>{s.users.find(u=>u.id===r.assignedTo)?.name||'Asociado asignado'}</b> · Aceptado {madridLocal(r.acceptedAt).replace('T',' ')}</p>}{r.status==='assigned'&&<p className={r.confirmedAt?'reservation-confirmed':'reservation-warning'}>{r.confirmedAt?'✓ CONFIRMADO':'PENDIENTE DE CONFIRMACIÓN'}</p>}{r.releaseRequest&&<p className="reservation-warning"><b>No puedo realizarlo:</b> {r.releaseRequest.reason} · Pendiente de decisión de Central</p>}{admin&&<p>Recordatorio: {s.reservationMail?.find(m=>m.reservation_id===r.id&&m.revision===r.revision)?.state||'Sin envío programado'}</p>}<div className="reservation-actions">{admin?<><button disabled={busy||!ready||r.status==='completed'} onClick={()=>setForm({...r,start:madridLocal(r.start)})}>Editar</button>{r.status==='pending'&&!r.published&&<button disabled={busy||!ready} onClick={()=>ask('reservation.publish',r)}>Publicar</button>}{r.status!=='completed'&&<button disabled={busy||!ready} onClick={()=>ask('reservation.republish',r)}>Republicar</button>}{!['completed','cancelled'].includes(r.status)&&<button disabled={busy||!ready} onClick={()=>ask('reservation.cancel',r)}>Cancelar</button>}{r.status==='assigned'&&!r.releaseRequest&&<button disabled={busy||!ready} onClick={()=>ask('reservation.complete',r)}>Marcar realizado</button>}</>:<>{r.status==='pending'&&r.published&&<button className="primary" disabled={busy||!ready} onClick={()=>ask('reservation.accept',r)}>ACEPTAR SERVICIO</button>}{r.assignedTo===user.id&&r.status==='assigned'&&!r.releaseRequest&&<>{!r.confirmedAt&&<button className="primary" disabled={busy||!ready} onClick={()=>ask('reservation.confirm',r)}>Confirmar que realizaré el servicio</button>}<button disabled={busy||!ready} onClick={()=>ask('reservation.release',r)}>No puedo realizarlo</button></>}</>}</div></article>;
 return <section className="reservations"><Toaster richColors/><div className="page-heading"><div><p className="eyebrow">TAXIMÉS · CENTRAL</p><h1>🚐 Reservas Especiales</h1><p>Monovolumen y Adaptado · Horarios de Madrid</p></div>{admin?<button className="primary" disabled={!ready||busy} onClick={()=>setForm({...empty})}>Nueva reserva</button>:<button className="secondary" onClick={()=>supabase().auth.signOut()}>Salir</button>}</div>{!ready&&<p role="status" className="reservation-warning">El módulo está pendiente de activar en el servidor. No se pueden guardar reservas.</p>}
 {!admin&&<nav className="reservation-tabs" aria-label="Área de reservas">{[['available','Servicios disponibles'],['mine','Mis servicios'],['notices','Avisos'],['profile','Mi perfil']].map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)}>{label}</button>)}</nav>}
 {admin&&<><div className="reservation-toolbar"><label>Vista<select value={mode} onChange={e=>setMode(e.target.value)}><option value="week">Semanal</option><option value="month">Mensual</option></select></label><label>Fecha<input type="date" value={day} onChange={e=>{if(e.target.value)setDay(e.target.value)}}/></label><label>Estado<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option>{Object.entries(names).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label></div><div className={'reservation-calendar '+mode}>{calendarDays(day,mode).map(d=><section key={d} className={'reservation-day '+(d===day?'selected':'')}><button onClick={()=>setDay(d)} aria-label={'Ver reservas del '+d}><time><span className="calendar-date-full">{new Date(d+'T12:00Z').toLocaleDateString('es-ES',{weekday:'short',day:'numeric',month:'short'})}</span><span className="calendar-date-short">{Number(d.slice(-2))}</span></time><span className="calendar-mobile-count">{rows.filter(r=>madridLocal(r.start).slice(0,10)===d).length||''}{rows.filter(r=>madridLocal(r.start).slice(0,10)===d).length>0&&<span aria-hidden="true">●</span>}</span></button>{rows.filter(r=>madridLocal(r.start).slice(0,10)===d).map(r=><button key={r.id} className={'reservation-chip '+r.status} onClick={()=>setDay(d)}>{madridLocal(r.start).slice(11)} · {r.kind==='ADAPTADO'?'♿':'🚐'}<br/>{names[r.status]}{r.status==='assigned'?(r.releaseRequest?' · Renuncia':r.confirmedAt?' · Confirmado':' · Sin confirmar'):r.published?' · Disponible':''}</button>)}</section>)}</div><h2>Servicios del {day}</h2></>}
 {(admin||tab==='available'||tab==='mine')&&<div className="reservation-list">{(()=>{const selected=rows.filter(r=>admin?madridLocal(r.start).slice(0,10)===day:tab==='mine'?r.assignedTo===user.id:r.status==='pending'&&r.published);return selected.length?selected.map(card):<p className="empty">No hay servicios en esta vista.</p>})()}</div>}
 {!admin&&tab==='notices'&&<section className="panel padded"><h2>Avisos de Central</h2><button disabled={busy} onClick={()=>act({type:'notification.read'})}>Marcar como leídos</button>{s.notifications.map(n=><p key={n.id}>{n.title} {!n.readBy.includes(user.id)&&'• Nuevo'}</p>)}{!s.notifications.length&&<p>Sin avisos.</p>}</section>}
 {!admin&&tab==='profile'&&<section className="panel padded"><h2>Mi perfil</h2><p>{user.name}</p><p>{user.email}</p><p>{profileLabel(user)}</p><p>Autorizaciones: {user.reservationTypes?.join(' · ')||'Ninguna'}</p><p>Central gestiona tu acceso y tus autorizaciones. Comunica cualquier cambio antes de aceptar servicios.</p></section>}
 {admin&&<details className="panel padded"><summary>Autorizaciones de asociados · Central</summary><form onSubmit={async e=>{e.preventDefault();await act({...access,type:'reservation.authorize'})}}><label>Cuenta<select required value={access.userId} onChange={e=>{const u=s.users.find(u=>u.id===e.target.value);setAccess({userId:e.target.value,memberId:u?.memberId||'',reservationTypes:u?.reservationTypes||[],status:u?.status==='active'?'active':'pending'})}}><option value="">Seleccionar</option>{s.users.filter(u=>!isAdmin(u)&&!u.demo).map(u=><option key={u.id} value={u.id}>{u.name} · {u.email} · {profileLabel(u)}</option>)}</select></label><label>Asociado del directorio<select required value={access.memberId} onChange={e=>setAccess({...access,memberId:e.target.value})}><option value="">Seleccionar</option>{s.members.filter(m=>m.status==='active'&&!m.demo).map(m=><option key={m.id} value={m.id}>{m.fleet} · {m.name}</option>)}</select></label>{reservationTypes.map(v=><label key={v} className="check-label"><input type="checkbox" checked={access.reservationTypes.includes(v)} onChange={e=>setAccess({...access,reservationTypes:e.target.checked?[...access.reservationTypes,v]:access.reservationTypes.filter((x:string)=>x!==v)})}/>{v==='MONOVOLUMEN'?'Monovolumen':'Adaptado'}</label>)}<label>Acceso<select value={access.status} onChange={e=>setAccess({...access,status:e.target.value})}><option value="active">Activo</option><option value="pending">Pendiente</option><option value="blocked">Bloqueado</option></select></label><p>Esta cuenta tendrá acceso únicamente al área de reservas. Los permisos de vehículos del directorio no otorgan acceso automáticamente.</p><button className="primary" disabled={busy||!ready}>Guardar autorización</button></form></details>}
 {admin&&<details className="panel padded"><summary>Auditoría de reservas</summary><button disabled={historyBusy||!ready} onClick={()=>history()}>Actualizar histórico</button>{events.map(e=><details key={e.id}><summary>{new Date(e.at).toLocaleString('es-ES',{timeZone:'Europe/Madrid'})} · {e.actorName} · {e.type}</summary><pre>{JSON.stringify({antes:e.before,después:e.after},null,2)}</pre></details>)}{historyLoaded&&!events.length&&<p>Sin movimientos.</p>}{cursor&&<button disabled={historyBusy} onClick={()=>history(true)}>Ver anteriores</button>}</details>}
 {form&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setForm(null)}}><DialogContent className="reservation-dialog"><DialogTitle>{form.id?'Editar reserva':'Nueva reserva'}</DialogTitle><DialogDescription>Datos operativos del servicio.</DialogDescription><form onSubmit={e=>{e.preventDefault();save()}}><label>Tipo<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}>{reservationTypes.map(t=><option key={t}>{t}</option>)}</select></label>{[['start','Fecha y hora (Madrid)','datetime-local'],['pickup','Recogida','text'],['destination','Destino','text'],['passengers','Pasajeros (opcional)','number']].map(([k,label,type])=><label key={k}>{label}<input required={k!=='passengers'} type={type} min={type==='number'?1:undefined} max={type==='number'?9:undefined} maxLength={300} value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Cliente<select value={form.customerType} onChange={e=>setForm({...form,customerType:e.target.value})}><option value="">No procede / sin especificar</option><option value="abonado">Abonado</option><option value="particular">Particular</option></select></label>{[['requirements','Requisitos especiales',500],['observations','Observaciones',1000]].map(([k,label,max])=><label key={String(k)}>{label}<textarea maxLength={Number(max)} value={form[String(k)]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<p>Incluye solo datos operativos. Evita nombres, teléfonos y datos médicos de pasajeros.</p><div className="reservation-actions"><button type="button" disabled={busy} onClick={()=>setForm(null)}>Cerrar</button><button className="primary" disabled={busy||!ready}>Guardar</button></div></form></DialogContent></Dialog>}
 {confirm&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setConfirm(null)}}><DialogContent className="reservation-dialog"><DialogTitle>{confirm.type==='reservation.accept'?'¿Aceptar este servicio?':'Confirmar acción'}</DialogTitle><DialogDescription>Revisa el servicio antes de confirmar.</DialogDescription><p>{confirm.kind} · {madridLocal(confirm.start).replace('T',' ')}</p><p>{confirm.pickup} → {confirm.destination}</p><p>{confirm.type==='reservation.republish'?'Se retirará la asignación actual y volverá a estar disponible.':confirm.type==='reservation.release'?'Central recibirá el motivo. El servicio seguirá asignado hasta que Central decida.':confirm.type==='reservation.accept'?'Al aceptar asumes la realización del servicio.':''}</p><form onSubmit={async e=>{e.preventDefault();if(await act({type:confirm.type,id:confirm.id,confirm:true,reason}))setConfirm(null)}}>{['reservation.release','reservation.cancel'].includes(confirm.type)&&<label>Motivo obligatorio<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>}<div className="reservation-actions"><button type="button" disabled={busy} onClick={()=>setConfirm(null)}>Volver</button><button className="primary" disabled={busy||!ready}>Confirmar</button></div></form></DialogContent></Dialog>}
 </section>;
}
