"use client";
import {useState} from 'react';
import {Plus,Search,ShieldAlert,Pencil,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Item,isAdmin} from '@/lib/model';

function madridNow(){const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const get=(k:string)=>parts.find(p=>p.type===k)?.value;return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`}
function SelectField({value,onChange,options,label}:{value:string,onChange:(v:string)=>void,options:{value:string,label:string}[],label:string}){return <Select value={value||undefined} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}

export default function Restrictions({members,user,lang,busy,act,memberId}:{members:Item[],user:Item,lang:string,busy:boolean,act:(action:Item,close?:boolean)=>Promise<boolean>,memberId?:string}){
 const t=(es:string,ca:string)=>lang==='ca'?ca:es,admin=isAdmin(user),now=madridNow();
 const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[status,setStatus]=useState('all'),[form,setForm]=useState<Item|null>(null),[remove,setRemove]=useState<Item|null>(null);
 const field=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
 const typeLabel=(kind:string)=>kind==='sanction'?t('Sanción','Sanció'):t('Incompatibilidad','Incompatibilitat');
 const state=(r:Item)=>r.deletedAt?'deleted':r.start>now?'scheduled':r.end&&r.end<=now?'ended':'current';
 const labels:Item={current:t('Vigente','Vigent'),scheduled:t('Programada','Programada'),ended:t('Finalizada','Finalitzada'),deleted:t('Borrada','Esborrada')};
 const date=(value:string)=>value?value.slice(0,10).split('-').reverse().join('/')+' '+value.slice(11,16):t('Sin fecha final','Sense data final');
 const stamp=(value:string)=>new Date(value).toLocaleString(lang==='ca'?'ca-ES':'es-ES',{timeZone:'Europe/Madrid',dateStyle:'short',timeStyle:'short'});
 const all=members.filter(m=>!memberId||m.id===memberId).flatMap(m=>(m.restrictions||[]).map((r:Item)=>({...r,memberId:m.id,member:m})));
 const rows=all.filter(r=>(admin||!r.deletedAt)&&(status==='deleted'?!!r.deletedAt:!r.deletedAt&&(status==='all'||state(r)===status))&&(kind==='all'||r.kind===kind)&&[r.member.fleet,r.member.license,r.member.name,r.title,r.reason].some(v=>String(v||'').toLocaleLowerCase().includes(query.toLocaleLowerCase()))).sort((a,b)=>String(b.created).localeCompare(String(a.created)));
 function create(){setForm({memberId:memberId||members.find(m=>m.status==='active')?.id||members[0]?.id||'',kind:'sanction',title:'',reason:'',start:now,end:''})}
 return <section className={'restrictions '+(memberId?'restrictions-compact':'')}>
  <div className={memberId?'panel-heading':'page-heading'}><div>{!memberId&&<p className="eyebrow">{t('SEGUIMIENTO DE ASOCIADOS','SEGUIMENT D’ASSOCIATS')}</p>}{memberId?<h3>{t('Sanciones e incompatibilidades','Sancions i incompatibilitats')}</h3>:<h1>{t('Sanciones e incompatibilidades','Sancions i incompatibilitats')}</h1>}{!memberId&&<p>{t('Consulta las medidas y los servicios restringidos de cada asociado.','Consulta les mesures i els serveis restringits de cada associat.')}</p>}</div>{admin&&<button type="button" className="primary" disabled={busy||!members.length} onClick={create}><Plus size={18}/>{t('Añadir','Afegeix')}</button>}</div>
  {!memberId&&<div className="restriction-filters"><label className="search-box"><Search size={18}/><input aria-label={t('Buscar sanciones e incompatibilidades','Cerca sancions i incompatibilitats')} placeholder={t('Flota, licencia, asociado o motivo…','Flota, llicència, associat o motiu…')} value={query} onChange={e=>setQuery(e.target.value)}/></label><SelectField label={t('Tipo','Tipus')} value={kind} onChange={setKind} options={[{value:'all',label:t('Todos los tipos','Tots els tipus')},{value:'sanction',label:t('Sanciones','Sancions')},{value:'incompatibility',label:t('Incompatibilidades','Incompatibilitats')}]}/></div>}
  <div className="restriction-status"><SelectField label={t('Estado','Estat')} value={status} onChange={setStatus} options={[{value:'all',label:t('Todos los estados','Tots els estats')},...['current','scheduled','ended',...(admin?['deleted']:[])].map(value=>({value,label:labels[value]}))]}/><small>{rows.length} {t('registros','registres')}{!admin?' · '+t('Solo consulta','Només consulta'):''}</small></div>
  <div className="restriction-list">{rows.map(r=><article key={r.id} className="panel padded restriction-card"><div className="flex-between"><span className={'tag '+(r.kind==='sanction'?'urgent':'blue')}>{typeLabel(r.kind)}</span><span className={'tag '+(state(r)==='current'?'pending':state(r)==='ended'?'resolved':'neutral')}>{labels[state(r)]}</span></div><h3>{r.title}</h3>{!memberId&&<p className="restriction-member"><strong>Flota {r.member.fleet} · {r.member.name}</strong><small>{t('Licencia','Llicència')} {r.member.license||'—'}{r.member.status==='inactive'?' · '+t('Asociado de baja','Associat de baixa'):''}</small></p>}<p className="restriction-reason">{r.reason}</p><div className="restriction-dates"><span><small>{t('Inicio','Inici')}</small>{date(r.start)}</span><span><small>{t('Fin','Fi')}</small>{date(r.end)}</span></div><small>{t('Registrado por','Registrat per')} {r.authorName} · {stamp(r.created)}{r.updated!==r.created?' · '+t('Editado por','Editat per')+' '+r.updatedByName:''}</small>{admin&&!r.deletedAt&&<div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setForm({id:r.id,memberId:r.memberId,kind:r.kind,title:r.title,reason:r.reason,start:r.start,end:r.end})}><Pencil size={15}/>{t('Editar','Edita')}</button><button className="secondary" disabled={busy} onClick={()=>setRemove(r)}><Trash2 size={15}/>{t('Borrar','Esborra')}</button></div>}{admin&&!!r.history?.length&&<details className="restriction-history"><summary>{t('Historial de cambios','Historial de canvis')} ({r.history.length})</summary>{r.history.map((h:Item,i:number)=><div key={i} className="comment"><strong>{h.authorName} · {h.action==='delete'?t('Borrado','Esborrat'):t('Edición','Edició')}</strong><small>{stamp(h.at)}</small><p>{t('Datos anteriores','Dades anteriors')}: {typeLabel(h.previous.kind)} · {h.previous.title}</p><p>{h.previous.reason}</p><small>{date(h.previous.start)} → {date(h.previous.end)}</small></div>)}</details>}</article>)}</div>
  {!rows.length&&<div className="panel empty"><ShieldAlert/><p>{t('No hay sanciones ni incompatibilidades para esta selección.','No hi ha sancions ni incompatibilitats per a aquesta selecció.')}</p></div>}
  <p className="info-line">{t('Registro informativo. Los bloqueos en la emisora se gestionan por separado. Horarios de Barcelona.','Registre informatiu. Els bloquejos a l’emissora es gestionen per separat. Horaris de Barcelona.')}</p>
  {admin&&<Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{form?.id?t('Editar registro','Edita el registre'):t('Añadir sanción o incompatibilidad','Afegeix una sanció o incompatibilitat')}</DialogTitle><DialogDescription>{t('Indica la medida, el motivo y su vigencia.','Indica la mesura, el motiu i la vigència.')}</DialogDescription></DialogHeader>{form&&<form className="modal-form" onSubmit={async e=>{e.preventDefault();if(await act({...form,type:'restriction.save'},false))setForm(null)}}><label>{t('Asociado','Associat')}{form.id||memberId?<strong>{members.find(m=>m.id===form.memberId)?.fleet} · {members.find(m=>m.id===form.memberId)?.name}</strong>:<SelectField label={t('Asociado','Associat')} value={form.memberId} onChange={v=>field('memberId',v)} options={members.map(m=>({value:m.id,label:m.fleet+' · '+m.name+(m.status==='inactive'?' · '+t('Baja','Baixa'):'' )}))}/>}</label><label>{t('Tipo','Tipus')}<SelectField label={t('Tipo de registro','Tipus de registre')} value={form.kind} onChange={v=>field('kind',v)} options={[{value:'sanction',label:t('Sanción','Sanció')},{value:'incompatibility',label:t('Incompatibilidad','Incompatibilitat')}]}/></label><label>{t('Medida o servicio afectado','Mesura o servei afectat')}<input required maxLength={160} value={form.title} placeholder={t('Ej.: Sin servicios / Incompatibilidad abonado 6464','Ex.: Sense serveis / Incompatibilitat abonat 6464')} onChange={e=>field('title',e.target.value)}/></label><label>{t('Motivo','Motiu')}<textarea required maxLength={5000} rows={4} value={form.reason} onChange={e=>field('reason',e.target.value)}/></label><div className="form-columns"><label>{t('Inicio','Inici')}<input required type="datetime-local" value={form.start} onChange={e=>field('start',e.target.value)}/></label><label>{t('Fin (opcional)','Fi (opcional)')}<input type="datetime-local" value={form.end} onChange={e=>field('end',e.target.value)}/></label></div><small>{t('Sin fecha final, el registro se considera indefinido.','Sense data final, el registre es considera indefinit.')}</small><div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setForm(null)}>{t('Cancelar','Cancel·la')}</button><button className="primary" disabled={busy||!form.memberId}>{busy?t('Guardando…','Desant…'):t('Guardar','Desa')}</button></div></form>}</DialogContent></Dialog>}
  {admin&&<AlertDialog open={!!remove} onOpenChange={v=>!v&&!busy&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('¿Borrar este registro?','Vols esborrar aquest registre?')}</AlertDialogTitle><AlertDialogDescription>{remove?.title} · Flota {remove?.member.fleet}. {t('Dejará de aparecer a los delegados. Administración conservará el historial del borrado.','Deixarà d’aparèixer als delegats. Administració conservarà l’historial de l’esborrat.')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>{t('Cancelar','Cancel·la')}</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(remove&&await act({type:'restriction.delete',memberId:remove.memberId,id:remove.id},false))setRemove(null)}}>{busy?t('Borrando…','Esborrant…'):t('Borrar','Esborra')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
 </section>;
}
