import {State,Item,isAdmin,coverage} from './model.ts';
const text=(x:any,max=5000)=>{if(typeof x!=='string'||!x.trim()||x.length>max)throw Error('Revisa los campos obligatorios.');return x.trim()};
const id=()=>crypto.randomUUID();
export function apply(s:State,u:Item,a:Item){const now=new Date().toISOString();const admin=()=>{if(!isAdmin(u))throw Error('Esta acción corresponde a administración.')};const find=(list:Item[],key:string)=>{const v=list.find(x=>x.id===key);if(!v)throw Error('No se ha encontrado el registro.');return v};const notify=(title:string,target='all',section='incidents')=>s.notifications.unshift({id:id(),title,target,section,created:now,readBy:[]});const files=(f:any)=>Array.isArray(f)?f.slice(0,5):[];
if(a.type==='register'){if(u.status==='active')throw Error('Tu acceso ya está aprobado.');u.name=text(a.name,100);u.phone=String(a.phone||'').slice(0,30);u.status='pending';if(!s.users.some(x=>x.id===u.id))s.users.push(u);notify('Nueva solicitud de acceso: '+u.name,'admins','users');return}
if(u.status!=='active')throw Error('Tu acceso está pendiente de aprobación.');
switch(a.type){
case 'restriction.save': {
admin();const m=find(s.members,a.memberId);const list:Item[]=m.restrictions||[];const old=a.id?find(list,a.id):null;
if(old?.deletedAt)throw Error('El registro está borrado.');
if(!['sanction','incompatibility'].includes(a.kind))throw Error('Tipo no válido.');
const validDate=(value:any)=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value)&&Number.isFinite(Date.parse(value+':00Z'))&&new Date(value+':00Z').toISOString().slice(0,16)===value;
if(!validDate(a.start)||(a.end&&!validDate(a.end))||(a.end&&a.end<=a.start))throw Error('Revisa las fechas: el final debe ser posterior al inicio.');
const next={kind:a.kind,title:text(a.title,160),reason:text(a.reason),start:a.start,end:a.end||'',updated:now,updatedBy:u.id,updatedByName:u.name};
if(old){const previous={...old};delete previous.history;old.history=[...(old.history||[]),{at:now,author:u.id,authorName:u.name,action:'edit',previous}];Object.assign(old,next)}
else{m.restrictions=[{id:id(),...next,created:now,author:u.id,authorName:u.name,history:[]},...list]}
notify('Sanciones e incompatibilidades actualizadas · Flota '+m.fleet,'all','restrictions');break}
case 'restriction.delete': {
admin();const m=find(s.members,a.memberId);const v=find(m.restrictions||[],a.id);if(v.deletedAt)throw Error('El registro ya está borrado.');
const previous={...v};delete previous.history;v.history=[...(v.history||[]),{at:now,author:u.id,authorName:u.name,action:'delete',previous}];v.deletedAt=now;v.deletedBy=u.id;v.deletedByName=u.name;
notify('Registro retirado · Flota '+m.fleet,'all','restrictions');break}
case 'incident.create': {const m=find(s.members,a.memberId);if(m.status!=='active')throw Error('El asociado está de baja.');if(!s.categories.includes(a.category))throw Error('Categoría no válida.');const driver=a.driver||'Vehículo/general';if(driver!=='Vehículo/general'&&!m.drivers.some((d:Item)=>d.name===driver))throw Error('Conductor no válido.');s.incidents.unshift({id:id(),memberId:m.id,memberSnapshot:{fleet:m.fleet,license:m.license,name:m.name},driver,category:a.category,title:text(a.title,160),description:text(a.description),priority:a.priority==='urgent'?'urgent':'normal',urgentReason:a.priority==='urgent'?text(a.urgentReason,500):'',status:'pending',author:u.id,authorName:u.name,created:now,comments:[],files:files(a.files),measures:[]});notify('Nueva incidencia · Flota '+m.fleet);break}
case 'incident.comment': {const v=find(s.incidents,a.id);if(['resolved','discarded','annulled'].includes(v.status))throw Error('La incidencia está cerrada.');v.comments.push({id:id(),text:text(a.text),author:u.id,authorName:u.name,created:now,files:files(a.files)});notify('Nueva aportación: '+v.title);break}
case 'incident.status': {admin();const v=find(s.incidents,a.id);if(!['pending','review','resolved','discarded','annulled'].includes(a.status))throw Error('Estado no válido.');const resolution=text(a.resolution);v.status=a.status;v.resolution=resolution;v.resolvedBy=u.name;v.resolvedAt=now;v.comments.push({id:id(),text:resolution,status:a.status,author:u.id,authorName:u.name,created:now,files:[]});notify('Actualización: '+v.title);break}
case 'incident.measure': {admin();const v=find(s.incidents,a.id);if(a.end&&a.start&&a.end<a.start)throw Error('La fecha final debe ser posterior.');v.measures.push({id:id(),type:text(a.measureType,100),reason:text(a.reason),start:a.start||'',end:a.end||'',author:u.name,created:now});notify('Medida registrada: '+v.title);break}
case 'member.edit': {admin();const v=find(s.members,a.id);v.history.push({at:now,author:u.name,previous:{...v,history:undefined}});for(const k of ['name','license','plate','model'])v[k]=String(a[k]??v[k]).trim().slice(0,150);v.requirements=Array.isArray(a.requirements)?a.requirements.map((x:any)=>String(x).slice(0,100)).slice(0,50):v.requirements;if(Array.isArray(a.drivers)){v.drivers=a.drivers.slice(0,8).map((d:Item,i:number)=>({id:d.id||id(),name:text(d.name,150),phone:String(d.phone||'').slice(0,30),shift:String(d.shift||'').slice(0,50)}))}v.manual=true;v.updated=now;break}
case 'import': {admin();if(!Array.isArray(a.members)||!a.members.length||a.members.length>2000)throw Error('El archivo no contiene un listado válido.');const seen=new Set();for(const m of a.members){text(m.fleet,30);if(seen.has(m.fleet))throw Error('Número de flota duplicado.');seen.add(m.fleet);text(m.name,150);if(!Array.isArray(m.drivers))throw Error('Conductores no válidos.');}for(const m of a.members){const old=s.members.find(x=>x.fleet===m.fleet);if(old){if(old.manual&&a.choices?.[old.fleet]!=='excel'&&a.choices?.[old.fleet]!=='manual')throw Error('Resuelve todos los cambios manuales antes de importar.');old.history.push({at:now,author:u.name,previous:{...old,history:undefined}});if(!old.manual||a.choices?.[old.fleet]==='excel'){for(const k of ['name','license','plate','model','requirements','drivers'])old[k]=m[k];old.manual=false}old.status='active';old.updated=now;old.demo=false}else{s.members.push({...m,id:id(),status:'active',history:[],manual:false,updated:now,demo:false})}}for(const m of s.members)if(!seen.has(m.fleet)){m.status='inactive';m.updated=now}notify('Listado de asociados actualizado','all','members');break}
case 'shift.create':case 'shift.edit': {const userId=a.userId||u.id;if(userId!==u.id)admin();const target=s.users.find(x=>x.id===userId&&x.status==='active');if(!target)throw Error('Delegado no válido.');const pattern=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/;if(!pattern.test(a.start)||!pattern.test(a.end)||!Number.isFinite(Date.parse(a.start))||Date.parse(a.end)<=Date.parse(a.start)||Date.parse(a.end)-Date.parse(a.start)>86400000)throw Error('El turno debe durar entre 1 minuto y 24 horas.');if(a.type==='shift.edit'){admin();const v=find(s.shifts,a.id);const previous=v.userId;Object.assign(v,{userId,start:a.start,end:a.end,status:'confirmed'});notify('Administración ha modificado tu turno',previous,'schedule')}else{s.shifts.push({id:id(),userId,start:a.start,end:a.end,status:'confirmed'})}notify('Turno asignado: '+a.start.replace('T',' '),userId,'schedule');break}
case 'shift.cancelRequest': {const v=find(s.shifts,a.id);if(v.userId!==u.id&&!isAdmin(u))throw Error('No puedes cancelar este turno.');v.status='cancel_requested';v.reason=text(a.reason,500);notify('Solicitud de cancelación de turno','admins','schedule');break}
case 'shift.cancelDecision': {admin();const v=find(s.shifts,a.id);if(v.status!=='cancel_requested')throw Error('No hay una solicitud pendiente.');v.status=a.approve?'cancelled':'confirmed';notify(a.approve?'Cancelación aprobada':'Cancelación rechazada',v.userId,'schedule');break}
case 'coverage.send':{admin();const result=coverage(s.shifts,a.week);if(!result.gaps.length)throw Error('El cuadrante está completo.');s.coverageRequests.unshift({id:id(),week:a.week,created:now,responses:[]});notify('Quedan turnos por cubrir · semana '+a.week,'all','schedule');break}
case 'coverage.reply':{const v=find(s.coverageRequests,a.id);v.responses=v.responses.filter((r:Item)=>r.userId!==u.id);v.responses.push({userId:u.id,name:u.name,text:text(a.text,1000),created:now});notify('Respuesta de cobertura: '+u.name,'admins','schedule');break}
case 'chat.send': {const channel=a.channel||'general';if(channel!=='general'&&channel!==u.id&&!isAdmin(u))throw Error('Conversación privada.');if(channel!=='general'&&!s.users.some(x=>x.id===channel))throw Error('Destinatario no válido.');if(!a.text?.trim()&&!a.files?.length)throw Error('Escribe un mensaje o adjunta un archivo.');s.messages.push({id:id(),channel,author:u.id,authorName:u.name,text:String(a.text||'').trim().slice(0,5000),created:now,files:files(a.files)});if(channel==='general')notify('Mensaje en el chat general','all','chat');else{notify('Nuevo mensaje privado',isAdmin(u)?channel:'admins','chat')}break}
case 'document.save': {admin();const title=text(a.title,160);let v=a.id?find(s.documents,a.id):null;const data={title,body:String(a.body||'').slice(0,20000),required:!!a.required,files:files(a.files),author:u.id,created:now,reads:[],version:v?v.version+1:1};if(!data.body.trim()&&!data.files.length)throw Error('Añade texto o un documento.');if(v)Object.assign(v,data);else s.documents.unshift({id:id(),...data});notify('Documento publicado: '+title,'all','documents');break}
case 'document.read':{const v=find(s.documents,a.id);if(!v.reads.some((r:Item)=>r.userId===u.id))v.reads.push({userId:u.id,name:u.name,created:now,version:v.version});break}
case 'poll.create': {admin();const options=Array.isArray(a.options)?a.options.map((x:any)=>text(x,150)):[];if(options.length<2||options.length>8||new Set(options).size!==options.length)throw Error('Introduce entre 2 y 8 opciones distintas.');if(!a.closes||Date.parse(a.closes)<=Date.now())throw Error('Selecciona una fecha futura.');s.polls.unshift({id:id(),title:text(a.title,160),options,anonymous:!!a.anonymous,closes:a.closes,votes:[],created:now});notify('Nueva encuesta: '+a.title,'all','polls');break}
case 'poll.vote': {const v=find(s.polls,a.id);if(Date.parse(v.closes)<Date.now())throw Error('La encuesta está cerrada.');if(!Number.isInteger(a.option)||!v.options[a.option])throw Error('Opción no válida.');v.votes=v.votes.filter((r:Item)=>r.userId!==u.id);v.votes.push({userId:u.id,option:a.option});break}
case 'user.update':{if(u.role!=='root')throw Error('Solo el administrador principal puede gestionar accesos.');const v=find(s.users,a.id);if(v.id===u.id)throw Error('No puedes retirar tu propio acceso.');if(!['admin','delegate'].includes(a.role)||!['active','blocked','pending'].includes(a.status))throw Error('Permiso no válido.');v.role=a.role;v.status=a.status;notify('Tu acceso ha sido actualizado',v.id,'home');break}
case 'categories':{admin();if(!Array.isArray(a.categories)||!a.categories.length)throw Error('Debe existir al menos una categoría.');s.categories=[...new Set(a.categories.map((x:any)=>text(x,100)))];break}
case 'notification.read': {for(const n of s.notifications)if(n.target==='all'||n.target===u.id||n.target==='admins'&&isAdmin(u)){if(!n.readBy.includes(u.id))n.readBy.push(u.id)}break}
default:throw Error('Acción desconocida.')}
s.audit.unshift({id:id(),type:a.type,author:u.name,created:now,record:a.id||''});s.audit=s.audit.slice(0,3000);s.notifications=s.notifications.slice(0,2000);
}
